#version 430 core

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) buffer IncrBuffer
{
	uint incr[];
};

layout(std430, binding = 1) buffer OutputBuffer
{
	uint data_out[];
};

uniform int n;
uniform int n_incr;

void main()
{
	const uint th_id = gl_GlobalInvocationID.x;
	const uint y = gl_WorkGroupID.y;
	const uint x = gl_WorkGroupID.x;
	if(th_id >= n) return;

	uint increment = incr[y * n_incr + x];
	data_out[y * n + th_id] += increment;
}