#version 430 core

layout (local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) buffer histogramBuffer
{
    uint histogram[];
};

layout(std430, binding = 1) buffer dataBuffer
{
    uint data_in[];
};

uniform uint n;
uniform uint bitStage;

void main()
{
    const uint threadID = gl_GlobalInvocationID.x;
    if(threadID >= n) return;
    const uint val = data_in[threadID];
    atomicAdd(histogram[(val >> bitStage) & 3], 1);
}